{"name": "test_failedcase_1", "status": "broken", "statusDetails": {"message": "AttributeError: 'list' object has no attribute 'items'", "trace": "cls = _pytest.runner.CallInfo, func = <function call_runtest_hook.<locals>.<lambda> at 0x0000026E075C7598>, when = 'setup'\nreraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)\n\n    @classmethod\n    def from_call(\n        cls,\n        func: \"Callable[[], TResult]\",\n        when: \"Literal['collect', 'setup', 'call', 'teardown']\",\n        reraise: Optional[\n            Union[Type[BaseException], Tuple[Type[BaseException], ...]]\n        ] = None,\n    ) -> \"CallInfo[TResult]\":\n        \"\"\"Call func, wrapping the result in a CallInfo.\n    \n        :param func:\n            The function to call. Called without arguments.\n        :param when:\n            The phase in which the function is called.\n        :param reraise:\n            Exception or exceptions that shall propagate if raised by the\n            function, instead of being wrapped in the CallInfo.\n        \"\"\"\n        excinfo = None\n        start = timing.time()\n        precise_start = timing.perf_counter()\n        try:\n>           result: Optional[TResult] = func()\n\nc:\\program files\\python36\\lib\\site-packages\\_pytest\\runner.py:340: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nc:\\program files\\python36\\lib\\site-packages\\_pytest\\runner.py:261: in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n..\\..\\AppData\\Roaming\\Python\\Python36\\site-packages\\pluggy\\hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n..\\..\\AppData\\Roaming\\Python\\Python36\\site-packages\\pluggy\\manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n..\\..\\AppData\\Roaming\\Python\\Python36\\site-packages\\pluggy\\manager.py:87: in <lambda>\n    firstresult=hook.spec.opts.get(\"firstresult\") if hook.spec else False,\nc:\\program files\\python36\\lib\\site-packages\\_pytest\\runner.py:156: in pytest_runtest_setup\n    item.session._setupstate.setup(item)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <_pytest.runner.SetupState object at 0x0000026E0696EDD8>, item = <Function test_failedcase_1>\n\n    def setup(self, item: Item) -> None:\n        \"\"\"Setup objects along the collector chain to the item.\"\"\"\n        needed_collectors = item.listchain()\n    \n        # If a collector fails its setup, fail its entire subtree of items.\n        # The setup is not retried for each item - the same exception is used.\n>       for col, (finalizers, exc) in self.stack.items():\nE       AttributeError: 'list' object has no attribute 'items'\n\nc:\\program files\\python36\\lib\\site-packages\\_pytest\\runner.py:488: AttributeError"}, "start": 1650033226462, "stop": 1650033226462, "uuid": "57eab5d2-c5fb-4f03-98bc-b10ae266b8f8", "historyId": "77e43856dcf54cca0f6731432dd67916", "testCaseId": "8d064ca44724c7ce6ad67022165d9e35", "fullName": "test_login.Test_webmodou#test_failedcase_1", "labels": [{"name": "feature", "value": "PC项目后台企业端接口测试用例"}, {"name": "severity", "value": "critical"}, {"name": "tag", "value": "run(order=2)"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_webmodou"}, {"name": "host", "value": "LAPTOP-HCLV5M2H"}, {"name": "thread", "value": "21252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}